name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 5.0.0
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  plugin_platform_interface: ^2.1.0
#  image_cropper_for_web: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter